apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: projectgroup1-test

resources:
  - deployment-recommendationservice.yaml
  - route-recommendationservice.yaml
  - service-recommendationservice.yaml
