apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: projectgroup1-test

resources:
  - deployment-communityservice.yaml
  - route-communityservice.yaml
  - service-communityservice.yaml
  - deployment-postgresql.yaml
  - service-postgresql.yaml
  - pvc-postgresql.yaml
