apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: projectgroup1-prod

resources:
  - ../../base

images:
  - name: ghcr.io/inholland-cloud-minor-2526/group1-recommendationservice
    newTag: main
