kind: Deployment
apiVersion: apps/v1
metadata:
  name: communityservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: communityservice
  template:
    metadata:
      labels:
        app: communityservice
    spec:
      containers:
        - name: communityservice
          image: "ghcr.io/coendv/group1-communityservice:dev"
          ports:
            - containerPort: 8083
              protocol: TCP
          env:
            - name: DB_HOST
              value: communityservice-postgresql
            - name: DB_PORT
              value: "5433"
            - name: DB_NAME
              value: communityservice
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@communityservice-postgresql:5433/communityservice
            - name: PORT
              value: "8083"
            - name: KEYCLOAK_URL
              value: http://userservice-keycloak:8080
            - name: KEYCLOAK_REALM
              value: entrepreneur-realm
            - name: KEYCLOAK_CLIENT_ID
              value: user-service
