kind: Deployment
apiVersion: apps/v1
metadata:
  name: communityservice
spec:
  selector:
    matchLabels:
      app: communityservice
  template:
    metadata:
      labels:
        app: communityservice
    spec:
      containers:
        - name: communityservice
          image: "ghcr.io/coendv/group1-communityservice:dev"
          ports:
            - containerPort: 8083
              protocol: TCP
            - containerPort: 9090
              protocol: TCP
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: communityservice-secrets
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: communityservice-secrets
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: communityservice-secrets
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: communityservice-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: communityservice-secrets
                  key: DB_PASSWORD
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: communityservice-secrets
                  key: DATABASE_URL
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: communityservice-secrets
                  key: PORT
            - name: KEYCLOAK_URL
              valueFrom:
                secretKeyRef:
                  name: communityservice-secrets
                  key: KEYCLOAK_URL
            - name: KEYCLOAK_REALM
              valueFrom:
                secretKeyRef:
                  name: communityservice-secrets
                  key: KEYCLOAK_REALM
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: communityservice-secrets
                  key: KEYCLOAK_CLIENT_ID
            - name: RECOMMENDATION_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: communityservice-secrets
                  key: RECOMMENDATION_SERVICE_URL
            - name: SERVICE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: communityservice-secrets
                  key: SERVICE_TOKEN
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
