apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: projectgroup1-test
namePrefix: communityservice-

commonLabels:
  app.kubernetes.io/name: communityservice
  app.kubernetes.io/part-of: slideshare-platform
  app.kubernetes.io/component: backend

resources:
  - deployment-communityservice.yaml
  - route-communityservice.yaml
  - service-communityservice.yaml
  - deployment-postgresql.yaml
  - service-postgresql.yaml
  - pvc-postgresql.yaml

configurations:
  - kustomizeconfig.yaml
