kind: Deployment
apiVersion: apps/v1
metadata:
  name: fotoshow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fotoshow
  template:
    metadata:
      labels:
        app: fotoshow
    spec:
      containers:
        - name: fotoshow
          image: 'image-registry.openshift-image-registry.svc:5000/projectgroup1-coen/fotoshow@sha256:cf1a50d1298d7b028c917b3de280e0cdf123748b0c40e25c853d0d7ee69fb54e'
          ports:
            - containerPort: 18181
              protocol: TCP
          env:
            - name: SLIDESHOW_EXTERNAL_DIR
              value: /data