kind: Deployment
apiVersion: apps/v1
metadata:
  name: chatservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatservice
  template:
    metadata:
      labels:
        app: chatservice
    spec:
      containers:
        - name: chatservice
          image: "ghcr.io/coendv/group1-chatservice:dev"
          ports:
            - containerPort: 8082
              protocol: TCP
          env:
            - name: DB_HOST
              value: chatservice-postgresql
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: chatservice
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@chatservice-postgresql:5432/chatservice
            - name: KEYCLOAK_URL
              value: http://userservice-keycloak:8080
            - name: KEYCLOAK_REALM
              value: entrepreneur-realm
            - name: KEYCLOAK_CLIENT_ID
              value: user-service
