kind: Deployment
apiVersion: apps/v1
metadata:
  name: chatservice
spec:
  selector:
    matchLabels:
      app: chatservice
  template:
    metadata:
      labels:
        app: chatservice
    spec:
      containers:
        - name: chatservice
          image: "ghcr.io/coendv/group1-chatservice:dev"
          ports:
            - containerPort: 8082
              protocol: TCP
            - containerPort: 9090
              protocol: TCP
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: chatservice-secrets
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: chatservice-secrets
                  key: DB_PORT

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: chatservice-secrets
                  key: DB_NAME

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: chatservice-secrets
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chatservice-secrets
                  key: DB_PASSWORD

            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: chatservice-secrets
                  key: DATABASE_URL

            - name: KEYCLOAK_URL
              valueFrom:
                secretKeyRef:
                  name: chatservice-secrets
                  key: KEYCLOAK_URL

            - name: KEYCLOAK_REALM
              valueFrom:
                secretKeyRef:
                  name: chatservice-secrets
                  key: KEYCLOAK_REALM

            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: chatservice-secrets
                  key: KEYCLOAK_CLIENT_ID

            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: chatservice-secrets
                  key: KEYCLOAK_CLIENT_SECRET

            - name: KEYCLOAK_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: chatservice-secrets
                  key: KEYCLOAK_ADMIN_USER

            - name: KEYCLOAK_ADMIN_PASS
              valueFrom:
                secretKeyRef:
                  name: chatservice-secrets
                  key: KEYCLOAK_ADMIN_PASS

            - name: USER_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: chatservice-secrets
                  key: USER_SERVICE_URL

            - name: NOTIFICATION_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: chatservice-secrets
                  key: NOTIFICATION_SERVICE_URL

            - name: APP_PORT
              valueFrom:
                secretKeyRef:
                  name: chatservice-secrets
                  key: APP_PORT

            - name: SERVICE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: chatservice-secrets
                  key: SERVICE_TOKEN

          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
