apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: projectgroup1-test
namePrefix: chatservice-

commonLabels:
  app.kubernetes.io/name: chatservice
  app.kubernetes.io/part-of: slideshare-platform
  app.kubernetes.io/component: backend

resources:
  - deployment-chatservice.yaml
  - route-chatservice.yaml
  - service-chatservice.yaml
  - deployment-postgresql.yaml
  - service-postgresql.yaml
  - pvc-postgresql.yaml

configurations:
  - kustomizeconfig.yaml
