kind: Deployment
apiVersion: apps/v1
metadata:
  name: recommendationservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
      containers:
        - name: recommendationservice
          image: "ghcr.io/coendv/group1-recommendationservice:dev"
          ports:
            - containerPort: 8084
              protocol: TCP
          env:
            - name: DB_HOST
              value: recommendationservice-postgresql
            - name: DB_PORT
              value: "5434"
            - name: DB_NAME
              value: recommendationservice
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@recommendationservice-postgresql:5434/recommendationservice
            - name: PORT
              value: "8084"
            - name: KEYCLOAK_URL
              value: http://userservice-keycloak:8080
            - name: KEYCLOAK_REALM
              value: entrepreneur-realm
            - name: KEYCLOAK_CLIENT_ID
              value: user-service
            - name: KEYCLOAK_AUDIENCE
              value: account
            - name: COMMUNITY_SERVICE_URL
              value: https://communityservice-communityservice-projectgroup1-prod.apps.inholland-minor.openshift.eu
