apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: projectgroup1-test
namePrefix: recommendationservice-

resources:
  - deployment-recommendationservice.yaml
  - route-recommendationservice.yaml
  - service-recommendationservice.yaml

configurations:
  - kustomizeconfig.yaml
