apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: projectgroup1-test
namePrefix: recommendationservice-

commonLabels:
  app.kubernetes.io/name: recommendationservice
  app.kubernetes.io/part-of: recommendation-app
  app.kubernetes.io/component: backend

resources:
  - deployment-recommendationservice.yaml
  - route-recommendationservice.yaml
  - service-recommendationservice.yaml
  - deployment-postgresql.yaml
  - service-postgresql.yaml
  - pvc-postgresql.yaml
  - servicemonitor-recommendationservice.yaml

configurations:
  - kustomizeconfig.yaml
