apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: projectgroup1-coen

secretGenerator:
  - name: postgresql-credentials
    envs:
      - .env

resources:
  - deployment-videoservice.yaml
  - route-videoservice.yaml
  - service-videoservice.yaml
  - deployment-postgresql.yaml
  - service-postgresql.yaml
  - pvc-postgresql.yaml
