apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: projectgroup1-prod

resources:
- ../../base

images:
- name: ghcr.io/coendv/group1-chatservice
  newTag: main
- name: ghcr.io/coendv/group1-communityservice
  newTag: main
- name: ghcr.io/coendv/group1-notificationservice
  newTag: main
- name: ghcr.io/coendv/group1-recommendationservice
  newTag: main
- digest: sha256:e6dc928ff484cf350675f345356bfeae733a8e99a766f4eec77f8f56b630387c
  name: ghcr.io/coendv/group1-userservice
  newName: ghcr.io/coendv/group1-userservice
- name: ghcr.io/coendv/group1-videoservice
  newTag: main
