apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: projectgroup1-prod

resources:
- ../../base

patches:
- path: ../../base/UserService/patch-keycloak-hostname-prod.yaml
  target:
    kind: Deployment
    name: userservice-keycloak

images:
- digest: sha256:209407bb6256367165a90e33ff8aeb943a641e47bb02581adf379664cb6a6bc4
  name: ghcr.io/coendv/group1-chatservice
  newName: ghcr.io/coendv/group1-chatservice
- digest: sha256:3d897468b27abe326e93186a080959f9ca769d82b85071350932983f958404eb
  name: ghcr.io/coendv/group1-communityservice
  newName: ghcr.io/coendv/group1-communityservice
- digest: sha256:2a72106b5abc4ec335f727f04130e8ddccf557e029db4bd89a0cf7e1a3740dd6
  name: ghcr.io/coendv/group1-notificationservice
  newName: ghcr.io/coendv/group1-notificationservice
- digest: sha256:d4de08ad46134fddab6b353cf6b9e45117000f0bba3c3113d6087d062e9fd0ce
  name: ghcr.io/coendv/group1-recommendationservice
  newName: ghcr.io/coendv/group1-recommendationservice
- digest: sha256:00ef473902c4a2d53b816dbf277ac1a04a28e1f8abfa5dabb4bcd336f13b4485
  name: ghcr.io/coendv/group1-userservice
  newName: ghcr.io/coendv/group1-userservice
- digest: sha256:662935402c6617ff9c0fd6a1622041f389e63e4f254d585fa986f2f16331a768
  name: ghcr.io/coendv/group1-videoservice
  newName: ghcr.io/coendv/group1-videoservice
