apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: projectgroup1-prod

resources:
  - ../../base

images:
  - name: ghcr.io/coendv/group1-chatservice
    newTag: main
  - name: ghcr.io/coendv/group1-communityservice
    newTag: main
  - name: ghcr.io/coendv/group1-notificationservice
    newTag: main
  - name: ghcr.io/coendv/group1-recommendationservice
    newTag: main
  - name: ghcr.io/coendv/group1-userservice
    newTag: main
  - name: ghcr.io/coendv/group1-videoservice
    newTag: main
