apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: projectgroup1-prod

resources:
- ../../base

images:
- digest: sha256:050875402c9c0adbd9445c6a3a310d73a8068c0c577cab53e6ec65eca54c1045
  name: ghcr.io/coendv/group1-chatservice
  newName: ghcr.io/coendv/group1-chatservice
- name: ghcr.io/coendv/group1-communityservice
  newTag: main
- digest: sha256:2d956b2af7fd2e5c4ce21990913a30e1fd5c454d3479983c386f92a9331db03a
  name: ghcr.io/coendv/group1-notificationservice
  newName: ghcr.io/coendv/group1-notificationservice
- name: ghcr.io/coendv/group1-recommendationservice
  newTag: main
- digest: sha256:8e1eacf1766d5dae6bfed4217ddf6c7e92a1343c5cebd90d979b39657f13fbe7
  name: ghcr.io/coendv/group1-userservice
  newName: ghcr.io/coendv/group1-userservice
- digest: sha256:14f2107ec0fd4f020743972fc5614a19c12748d992702266e001e0a95b79b5c6
  name: ghcr.io/coendv/group1-videoservice
  newName: ghcr.io/coendv/group1-videoservice
