apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: projectgroup1-prod

resources:
- ../../base

patches:
- path: ../../base/UserService/patch-keycloak-hostname-prod.yaml
  target:
    kind: Deployment
    name: userservice-keycloak

images:
- digest: sha256:8e465bb2360e09bb4b4523abb5447a96e3337ddce4c1fb0f112b8d2354300227
  name: ghcr.io/coendv/group1-chatservice
  newName: ghcr.io/coendv/group1-chatservice
- digest: sha256:20dcf19ee4db2d6e18c4860437a65e0346d441120796cc7bddfcb20d6dc69a55
  name: ghcr.io/coendv/group1-communityservice
  newName: ghcr.io/coendv/group1-communityservice
- digest: sha256:1c7d6a0a205e9d989b492fd708103e16a826929f120b904464adcc530f07519b
  name: ghcr.io/coendv/group1-notificationservice
  newName: ghcr.io/coendv/group1-notificationservice
- digest: sha256:fefc7436d35802b21aca19dcbd8476660e6d4219765e9c3d12991d4dbabf6696
  name: ghcr.io/coendv/group1-recommendationservice
  newName: ghcr.io/coendv/group1-recommendationservice
- digest: sha256:2a1e60f0550de199e697b8553a148561d6d3c28a2c774515415cfd79dd05434f
  name: ghcr.io/coendv/group1-userservice
  newName: ghcr.io/coendv/group1-userservice
- digest: sha256:12172c597052e7aefd7275af067491fa43382fd6e968ff25079de004b3968a99
  name: ghcr.io/coendv/group1-videoservice
  newName: ghcr.io/coendv/group1-videoservice
