apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: projectgroup1-prod

resources:
- ../../base

images:
- name: ghcr.io/coendv/group1-chatservice
  newTag: main
- name: ghcr.io/coendv/group1-communityservice
  newTag: main
- name: ghcr.io/coendv/group1-notificationservice
  newTag: main
- name: ghcr.io/coendv/group1-recommendationservice
  newTag: main
- name: ghcr.io/coendv/group1-userservice
  newTag: main
- digest: sha256:14f2107ec0fd4f020743972fc5614a19c12748d992702266e001e0a95b79b5c6
  name: ghcr.io/coendv/group1-videoservice
  newName: ghcr.io/coendv/group1-videoservice
