apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: projectgroup1-prod

resources:
- ../../base

patches:
- path: ../../base/UserService/patch-keycloak-hostname-prod.yaml
  target:
    kind: Deployment
    name: userservice-keycloak

images:
- digest: sha256:97e41ea9dd9770e3061831d86270f8d1cf2fa6992e63f991da6192def9230b43
  name: ghcr.io/coendv/group1-chatservice
  newName: ghcr.io/coendv/group1-chatservice
- digest: sha256:5878d4a943d1665d474788d437edd4f09e0d7f7462cb6969becda1cc7df50b83
  name: ghcr.io/coendv/group1-communityservice
  newName: ghcr.io/coendv/group1-communityservice
- digest: sha256:59198eb08c524555b85277526cbbfc045882cd184ba2237d57b8ffeae23c695c
  name: ghcr.io/coendv/group1-notificationservice
  newName: ghcr.io/coendv/group1-notificationservice
- digest: sha256:d7a072121a96d7a8ece2f9f5ab52a5526f83bfbd259d91b0881c4784729484f7
  name: ghcr.io/coendv/group1-recommendationservice
  newName: ghcr.io/coendv/group1-recommendationservice
- digest: sha256:bcc1d3892a62754d43b4d0a0a6beb16e154bcfca27e3904449b0f4725842d1e0
  name: ghcr.io/coendv/group1-userservice
  newName: ghcr.io/coendv/group1-userservice
- digest: sha256:4ab6d2d57f20b8597f870e65d5d42756739a3d2569b4f0c7c6fd3bf1e5ddce26
  name: ghcr.io/coendv/group1-videoservice
  newName: ghcr.io/coendv/group1-videoservice
