apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: projectgroup1-prod

resources:
- ../../base

patches:
- path: ../../base/UserService/patch-keycloak-hostname-prod.yaml
  target:
    kind: Deployment
    name: userservice-keycloak

images:
- digest: sha256:ef2fe2938abba069a2f5368c068d68474edaecf13a6fd573d4b8b115714de4c1
  name: ghcr.io/coendv/group1-chatservice
  newName: ghcr.io/coendv/group1-chatservice
- digest: sha256:b8fa203a15b14236ec50f03aa07edeee4010da6816a95118a17fb070388945f9
  name: ghcr.io/coendv/group1-communityservice
  newName: ghcr.io/coendv/group1-communityservice
- digest: sha256:f60e3a62d1a49fa5c2352603d13e635162082325b443f8e5445fe1e9b96ffc06
  name: ghcr.io/coendv/group1-notificationservice
  newName: ghcr.io/coendv/group1-notificationservice
- digest: sha256:ba9281bbfc32f75b0d9b612b4d432dec721bf05a24370e42b717adbab6c73373
  name: ghcr.io/coendv/group1-recommendationservice
  newName: ghcr.io/coendv/group1-recommendationservice
- digest: sha256:ab43bde27c9655a0f9a943cba810250f4534dfdcfbbba126960f227a2955591a
  name: ghcr.io/coendv/group1-userservice
  newName: ghcr.io/coendv/group1-userservice
- digest: sha256:9e90f3e45f56bf7ef1d1381e99abd4b71d0fd49e362032f1d2f947e8d7b2cc50
  name: ghcr.io/coendv/group1-videoservice
  newName: ghcr.io/coendv/group1-videoservice
