apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: projectgroup1-prod

resources:
- ../../base

patches:
- path: ../../base/UserService/patch-keycloak-hostname-prod.yaml
  target:
    kind: Deployment
    name: userservice-keycloak

images:
- digest: sha256:8e465bb2360e09bb4b4523abb5447a96e3337ddce4c1fb0f112b8d2354300227
  name: ghcr.io/coendv/group1-chatservice
  newName: ghcr.io/coendv/group1-chatservice
- digest: sha256:6fd53b3433f4a6f2cbe583abdb0b7a292a16d9603a6622dc2a3bc468e9ceb167
  name: ghcr.io/coendv/group1-communityservice
  newName: ghcr.io/coendv/group1-communityservice
- digest: sha256:44f5848bd5fa015dc9270946442b17817e145f65c0e369fb998beacd660d6189
  name: ghcr.io/coendv/group1-notificationservice
  newName: ghcr.io/coendv/group1-notificationservice
- digest: sha256:d5d80d3455b49044231f6421c2c4f173397b31beeb541d9182c841baab6e5fe6
  name: ghcr.io/coendv/group1-recommendationservice
  newName: ghcr.io/coendv/group1-recommendationservice
- digest: sha256:b9a25774825b0e22a411971bf04d562ba271bbc539c0438d949d894d174b16e3
  name: ghcr.io/coendv/group1-userservice
  newName: ghcr.io/coendv/group1-userservice
- digest: sha256:640196feded099362ae13bbaf25095a79afda8616f359929b9b2a47516ad648f
  name: ghcr.io/coendv/group1-videoservice
  newName: ghcr.io/coendv/group1-videoservice
