apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: projectgroup1-test
namePrefix: notificationservice-

resources:
  - deployment-notificationservice.yaml
  - route-notificationservice.yaml
  - service-notificationservice.yaml

configurations:
  - kustomizeconfig.yaml
