apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: projectgroup1-test
namePrefix: notificationservice-

commonLabels:
  app.kubernetes.io/name: notificationservice
  app.kubernetes.io/part-of: notification-app
  app.kubernetes.io/component: backend

resources:
  - deployment-notificationservice.yaml
  - route-notificationservice.yaml
  - service-notificationservice.yaml
  - hpa-notificationservice.yaml

configurations:
  - kustomizeconfig.yaml
