kind: Deployment
apiVersion: apps/v1
metadata:
  name: userservice
spec:
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: userservice
          image: "ghcr.io/coendv/group1-userservice:dev"
          ports:
            - containerPort: 8081
              protocol: TCP
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: userservice-secrets
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: userservice-secrets
                  key: DB_PORT

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: userservice-secrets
                  key: DB_NAME

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: userservice-secrets
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: userservice-secrets
                  key: DB_PASSWORD

            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: userservice-secrets
                  key: DATABASE_URL

            - name: APP_PORT
              valueFrom:
                secretKeyRef:
                  name: userservice-secrets
                  key: APP_PORT

            - name: KEYCLOAK_URL
              valueFrom:
                secretKeyRef:
                  name: userservice-secrets
                  key: KEYCLOAK_URL

            - name: KEYCLOAK_REALM
              valueFrom:
                secretKeyRef:
                  name: userservice-secrets
                  key: KEYCLOAK_REALM

            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: userservice-secrets
                  key: KEYCLOAK_CLIENT_ID

            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: userservice-secrets
                  key: KEYCLOAK_CLIENT_SECRET

            - name: KEYCLOAK_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: userservice-secrets
                  key: KEYCLOAK_ADMIN_USER

            - name: KEYCLOAK_ADMIN_PASS
              valueFrom:
                secretKeyRef:
                  name: userservice-secrets
                  key: KEYCLOAK_ADMIN_PASS

            - name: USER_SERVICE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: userservice-secrets
                  key: USER_SERVICE_TOKEN
            - name: NOTIFICATION_SERVICE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: userservice-secrets
                  key: NOTIFICATION_SERVICE_TOKEN
            - name: SENDER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: userservice-secrets
                  key: SENDER_EMAIL
            - name: NOTIFICATION_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: userservice-secrets
                  key: NOTIFICATION_SERVICE_URL
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
