kind: Deployment
apiVersion: apps/v1
metadata:
  name: userservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: userservice
          image: "ghcr.io/coendv/group1-userservice:dev"
          ports:
            - containerPort: 8081
              protocol: TCP
          env:
            - name: DB_HOST
              value: userservice-postgresql
            - name: DB_PORT
              value: "5431"
            - name: DB_NAME
              value: userservice
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@userservice-postgresql:5431/userservice
            - name: KEYCLOAK_URL
              value: http://keycloak:8080
            - name: KEYCLOAK_REALM
              value: simpleslideshow
            - name: KEYCLOAK_CLIENT_ID
              value: simpleslideshow-client
            - name: KEYCLOAK_CLIENT_SECRET
              value: changeme
            - name: KEYCLOAK_ADMIN_USER
              value: admin
            - name: KEYCLOAK_ADMIN_PASS
              value: admin
