apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: projectgroup1-test
namePrefix: userservice-

commonLabels:
  app.kubernetes.io/name: userservice
  app.kubernetes.io/part-of: user-app
  app.kubernetes.io/component: backend

resources:
  - deployment-userservice.yaml
  - route-userservice.yaml
  - service-userservice.yaml
  - deployment-postgresql.yaml
  - service-postgresql.yaml
  - pvc-postgresql.yaml
  - deployment-keycloak.yaml
  - service-keycloak.yaml
  - route-keycloak.yaml

configurations:
  - kustomizeconfig.yaml
