kind: Deployment
apiVersion: apps/v1
metadata:
  name: ngrok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngrok
  template:
    metadata:
      labels:
        app: ngrok
    spec:
      containers:
        - name: ngrok
          image: ngrok/ngrok:latest
          ports:
            - containerPort: 4040
              protocol: TCP
              name: web-ui
          args:
            - "http"
            - "--log=stdout"
            - "--log-level=info"
            - "--domain=$(NGROK_DOMAIN)"
            - "videoservice-service:8085"
          env:
            - name: NGROK_AUTHTOKEN
              valueFrom:
                secretKeyRef:
                  name: ngrok-secret
                  key: authtoken
            - name: NGROK_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: ngrok-secret
                  key: domain
                  optional: true
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
