apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: projectgroup1-test
namePrefix: videoservice-

commonLabels:
  app.kubernetes.io/name: videoservice
  app.kubernetes.io/part-of: video-app
  app.kubernetes.io/component: backend

resources:
  - deployment-videoservice.yaml
  - route-videoservice.yaml
  - service-videoservice.yaml
  - deployment-postgresql.yaml
  - service-postgresql.yaml
  - pvc-postgresql.yaml
  - deployment-ngrok.yaml
  - service-ngrok.yaml
  - route-ngrok.yaml
  - servicemonitor-videoservice.yaml

configurations:
  - kustomizeconfig.yaml
